
title      : "LEAD"
description: "Local Expert Action Directory"
author     : '#ASKnet'
screenshot: https://raw.githubusercontent.com/ASKnetCommunity/LEAD/development/assets/images/screenshot.jpg

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lead.asknet.community" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-remote-include
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  sass_dir: assets/scss
  style: compressed

# Collections

collections:
  profiles:
    output: true
    output_ext: .html
    permalink: /profiles/:path/

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.text
  - README.md
  - SECURITY.md
