name: Change Profile
description: Submit changes to your already existing profile
title: "Change Profile for ..."
labels: [ChangeProfile]
body:
  - type: markdown
    attributes:
      value: |
        Here you can submit changes to your profile, if it exists already. 
                
  - type: input
    id: name
    attributes:
      label: Name
      description: "your full name"
    validations:
      required: true  
  - type: input
    id: profile-url
    attributes:
      label: Profile Link
      description: "Please input here the link (URL) to your profile on the LEAD website, or (if you're familiar) the link to your .md file in the _posts folder"
    validations:
      required: true  
  - type: checkboxes
    id: tochange
    attributes:
      label: What needs to be changed?
      description: "Please check the boxes for all information that you want to change. Leave boxes unticked if you want that respective information to remain unchanged in your profile. <br\>Please keep in mind: If you want to add some infos (e.g. a region) but want to keep your existing info (e.g. an old region that you still frequently visit), you need to write both in the text field. In our example you need to write your old region (maybe copy from your profile) and the new region. Otherwise, the LEAD maintainer has no way of knowing if the old infos need to be kept or should be overwritten with the new infos."
      options:
        - label: Change Name
          required: false
        - label: Change Region
          required: false
        - label: Change Hub
          required: false
        - label: Change Skills
          required: false
        - label: Change Description
          required: false
        - label: Change Profile Image
          required: false
    validations:
      required: true
  - type: textarea
    id: changes
    attributes:
      label: Description
      description: "Here, please write down the changes that you want to make in your profile. A LEAD maintainer will copy these changes to your profile."
    validations:
      required: true
