name: New Profile
description: Create a new profile
title: "Create Profile for ..."
labels: [New Profile]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out some informations about you! Great to have you as part of the LEAD network! Your data will be published on the LEAD page. If you already have a profile which you want to update, please use the following tutorial: (needs to be written)
                
  - type: input
    id: name
    attributes:
      label: Name
      description: "your full name"
    validations:
      required: true  
  - type: input
    id: region
    attributes:
      label: Region
      description: "In which region are you active? You can add several regions/city/your country by separating them with commas."
      placeholder: "e.g. Uganda, Rhino-Camp"
    validations:
      required: true
  - type: input
    id: hub
    attributes:
      label: Hub
      description: "If you are active in a hub, you can indicate here in which"
      placeholder: "Hub Name"
    validations:
      required: false
  - type: checkboxes
    id: skills
    attributes:
      label: Skills
      description: What are your skills? You can specify other skills in your description text
      options:
        - label: Hardware
          required: false
        - label: Repair
          required: false
        - label: Software
          required: false
        - label: Entrepreneurship
          required: false
        - label: Media Production
          required: false
        - label: Gender Equality Awareness
          required: false
        - label: Trauma Healing
          required: false
        - label: Financial Literacy
          required: false
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Tell others about yourself, your story, your expertise in some short words or several paragraphs.
    validations:
      required: true
  - type: textarea
    id: profile-image
    attributes:
      label: Profile Image
      description: You can upload an image for your profile by dragging & dropping into this textarea or clicking on the bottom of this textarea and select your image. 
    validations:
      required: true
