name: New Profile
description: Create a new profile
title: "Create Profile for ..."
labels: ["New Profile"]
body:
  - type: markdown
    attributes:
      value: |
        "Thank you for taking the time to fill out some informations about you! Great to have you as part of the LEAD network! If you already have a profile which you want to update, please use the following tutorial: [todo:write tutorial]"
                
  - type: input
    id: name
    attributes:
      label: Name
      description: "This name will be published on the LEAD page"
    validations:
      required: true  
  - type: input
    id: region
    attributes:
      label: Region
      description: "In which region are you active"
    validations:
      required: true
  - type: input
    id: hub
    attributes:
      label: Hub
      description: "If you are active in a hub, you can indicate here in which"
      placeholder: "Hub Name"
    validations:
      required: false
  - type: checkboxes
    id: skills
    attributes:
      label: Skills
      description: What are your skills?
      options:
        - label: Repair
          required: false
        - label: Computer
          required: false
        - label: Github
          required: false
        - label: Any else (please specify in the description!)
          required: false
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe yourself in short words
    validations:
      required: true
  - type: textarea
    id: profile-image
    attributes:
      label: Profile Image
      description: You can upload a images for your profile by drag and drop into this textarea or click on the bottom of this textarea "Attach files by dragging & dropping, selecting or pasting them."
    validations:
      required: true
