name: New Profile
description: Create a new profile
title: "Create Profile for ..."
labels: [NewProfile]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out some informations about you! Great to have you as part of the LEAD network! Your data will be published on the LEAD page. Here you can find a tutorial to help you in filling out your information: [link](https://github.com/ASKnetCommunity/LEAD/wiki/Tutorial-%22New-Profile%22-(for-ASKnet-Peers)). If you already have a profile which you want to update, please use [this link](https://github.com/ASKnetCommunity/LEAD/issues/new?assignees=&labels=ChangeProfile&template=change-profile.yml&title=Change+Profile+for+...) to submit your changes. 
                
  - type: input
    id: name
    attributes:
      label: Name
      description: "your full name"
    validations:
      required: true  
  - type: input
    id: country
    attributes:
      label: Country
      description: "In which country are you active?"
      placeholder: "e.g. South Sudan"
    validations:
      required: true
  - type: input
    id: region
    attributes:
      label: Region
      description: "In which region are you active? You can add several regions or cities by separating them with commas."
      placeholder: "e.g. Juba, Rhino-Camp, Berlin"
    validations:
      required: true
  - type: input
    id: hub
    attributes:
      label: Hub
      description: "If you are active in a hub, you can indicate here in which"
      placeholder: "Hub Name"
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Contact 
        
        How and where do you want to be contacted? Fill in your contact details, and leave the fields blank that you don't use. We'd kindly ask to give at least one contact option. 

  - type: input
    id: email
    attributes:
      label: E-Mail
      description: "your E-Mail address"
    validations:
      required: false
  - type: input
    id: tel
    attributes:
      label: Phone
      description: "your phone number"
    validations:
      required: false

  - type: checkboxes
    id: skills
    attributes:
      label: Skills
      description: What are your skills? You can specify other skills in your description text
      options:
        - label: Hardware
          required: false
        - label: Repair
          required: false
        - label: Software
          required: false
        - label: Entrepreneurship
          required: false
        - label: Media Production
          required: false
        - label: Gender Equality Awareness
          required: false
        - label: Trauma Healing
          required: false
        - label: Financial Literacy
          required: false
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Tell others about yourself, your story, your expertise in some short words or several paragraphs.
    validations:
      required: true
  - type: textarea
    id: profile-image
    attributes:
      label: Profile Image
      description: You can upload an image for your profile by dragging & dropping into this textarea or clicking on the bottom of this textarea and select your image. 
    validations:
      required: true
