name: 'update profiles.csv'

on:
  push:
    branches: [ main ]
    paths:
      - '_profiles/**'
  workflow_dispatch:

job:
  extract:
    name: 'run extract.py'
    runs-on: ubuntu-latest
    steps:

      - name: "Check out the repo"
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: "Setup Python 3"
        uses: actions/setup-python@v2
        with:
            python-version: '3.x'

      - name: 'run extract.py'
        run: 'python3 extract.py'
